name: Generate ASCII Artwork

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it. 
    # This means the github runner can access your repo allowing it to run commands such as ls & cat
    - name: checkout action
      uses: actions/checkout@v4

    # Install third party program from ubuntu cowsay on he github runner to generate the artwork
    - name: Install program cowsay
      run: sudo apt-get install cowsay -y 

    # Using third party libary cowsay --> The cowsay command is a command-line utility that generates ASCII art images of cows or other animals speaking or thinking
    - name: Execute cowsay cmd 
      run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.log

    # Test to make sure file exists 
    - name: Test file exists
      run: grep -i "dragon" dragon.log

    # Read file dragon.log
    - name: Read file 
      run: cat dragon.log
    
    - name: Checkout repo files
      run: ls -ltra
