name: Generate ASCII Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps: 
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y 
    
    - name: Execute cowsay cmd 
      run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.log

    # Upload Actions Artifacts from your Workflow Runs.
    - uses: actions/upload-artifact@v4
      with:
      # Name of the artifact to upload.
      # Optional. Default is 'artifact'
        name: dragon_text_file 
        path: dragon.log

  build_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
    # Download Actions Artifacts from your Workflow Runs.
    - uses: actions/download-artifact@v4
      with:
      # Name of the artifact to download.
      # If unspecified, all artifacts for the run are downloaded.
      # Optional.
        name: dragon_text_file 

    - name: Test file exists
      run: grep -i "dragon" dragon.log
     
  build_job_3:
    runs-on: ubuntu-latest
    needs: build_job_2
    steps:
    # Download Actions Artifacts from your Workflow Runs.
    - uses: actions/download-artifact@v4
      with:
      # Name of the artifact to download.
      # If unspecified, all artifacts for the run are downloaded.
      # Optional.
        name: dragon_text_file 

    - name: Read files
      run: ls -ltra

    - name: Deploy
      run: echo deploy ... .. . 

  # generate_ascii_artwork:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repo files
  #     run: ls -ltra

  #   # Run shell script from root folder
  #   - name: Run generate_ascii_artwork.sh
  #     run: |
  #       chmod +x generate_ascii_artwork.sh
  #       ./generate_ascii_artwork.sh 

    # # Install third party program from ubuntu cowsay on he github runner to generate the artwork
    # - name: Install program cowsay
    #   run: sudo apt-get install cowsay -y 

    # # Using third party libary cowsay --> The cowsay command is a command-line utility that generates ASCII art images of cows or other animals speaking or thinking
    # - name: Execute cowsay cmd 
    #   run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.log

    # # Test to make sure file exists 
    # - name: Test file exists
    #   run: grep -i "dragon" dragon.log

    # # Read file dragon.log
    # - name: Read file 
    #   run: cat dragon.log
    
    # - name: Checkout repo files
    #   run: ls -ltra
